import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  sidebar: [
    'index',
    'particle',
    'verlet',
    // springbone
    {
      type: 'category',
      label: 'SpringBone',
      link: { type: 'doc', id: 'springbone/index' },
      items: [
        'springbone/rocketjump',
        'springbone/vrmspringbone',
      ],
    },
    // cloth
    {
      type: 'category',
      label: 'Cloth',
      items: [
        'cloth/index',
        {
          type: 'category',
          label: '実装例',
          link: { type: 'doc', id: 'cloth/impl/index' },
          items: [
            'cloth/impl/cloth_yr',
            'cloth/impl/cloth_pbd',
          ]
        },
      ],
    },
    {
      type: 'category',
      label: '参考',
      items: [
        'refrence/pbd',
        'refrence/xpbd',
        'refrence/mass_spring_model',
      ]
    }
  ],
};

export default sidebars;
